services:
  pgserver:
    image: postgres:latest
    container_name: pgserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - dbnet
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=soccernowdb
    restart: unless-stopped

  # APP*****************************************
  springbootapp:
    image: myapp:latest
    build:
      context: .
    container_name: java_app
    restart: unless-stopped
    depends_on:
      - pgserver
    networks:
      - dbnet
    ports:
      - "8080:8080"

volumes:
  postgres-data:


networks:
  dbnet:
    driver: bridge
